### ISSUE TITLE
failed to parse rust compiler version

### ISSUE THREAD

**Issue by tkkcc** [MatrixDev/GradleAndroidRustPlugin#1]
![image](https://user-images.githubusercontent.com/17373509/231124330-e46dde66-7342-47eb-83a6-5726924c97f3.png)

**Comment by MatrixDev** [comment]
@tkkcc, I didn't test plugin with nightly, only with stable rust. thansfully this one should be trivial to fix

**Comment by MatrixDev** [comment]
@tkkcc, your issue should be fixed in version 0.3.2
